version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Odei0React!'
      MSSQL_PID: 'Express'
      MSSQL_TCP_PORT: '1433'
      MSSQL_DATABASE: 'master'
      MSSQL_ENABLE_HSTS: '0'
    ports:
      - '1433:1433'

  core:
    build:
      context: ./Core/Core
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - '8080:8080'
    depends_on:
      - sql-server

  risk:
    build:
      context: ./Risk/Risk
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - '8081:8081'
    depends_on:
      - sql-server
