version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Odei0React!'
      MSSQL_PID: 'Express'
      MSSQL_TCP_PORT: '1433'
      MSSQL_DATABASE: 'master'
      MSSQL_ENABLE_HSTS: '0'
    ports:
      - '1433:1433'
